// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package go_graphql

type NewUser struct {
	FirstName string `json:"first_name"`
	LastName  string `json:"last_name"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}
